### ISSUE TITLE
What's the use for this project?

### ISSUE THREAD

**Issue by 461353349** [thelfer/tfel-editor#1]
Can you give a detailed description?

**Comment by thelfer** [comment]
Dear 461353349,

Thank your for asking. I like the idea that the first issue associated with `qemacs` is related to its purpose. I think that I will never close this issue.

The primary idea behind this project is to have a GUI editor which can leverage the full power of the tools that I have developped, for example `MFront` (see <http://tfel.sourceforge.net>
 and <https://www.sciencedirect.com/science/article/pii/S0898122115003132>), `MTest`, `Licos` (<https://www.sciencedirect.com/science/article/pii/S0029549315003842>) and bring this power to standard engineers.

Those tools are mostly based in text files, so I decided to create a text editor:

- which is inspired by `GNU Emacs` main concepts (such as buffers, major modes, etc..). For me, `GNU Emacs` is definitively the best text editor.
- that would make full use of the `Qt` library (hence the name, `qemacs=Qt+emacs`)

This text editor is meant to have the following advantages:

- Use `C++` as the main language (mostly by personal taste). I am definitively not a `LISP` programmer and found easier to create my own text editor than learning a new language (more precisely, I found it more fun and usefull to learn `Qt` than `LISP`). May be I shall also one day allow user extensions (mostly major modes) in `python`.
- Portability (Linux is the primary target, but Windows/FreeBSD/Mac Os are also considered as first class targets).
- The ability to use Windows-type short-cuts for users not at ease with `GNU Emacs` ones and have all the power of the editor accessible from the GUI.
- The ability to integrate this editor into external software. More precisely, the projet is decomposed in a shared library caleed `TFELQEmacs` and an executable `qemacs`. The library provides the main widgets (for example the `QEmacsWidget`) that can be reused out of the box.
- Develop some ideas of my own.

I also created major modes for the tools that I use daily:

- `Cast3M` <http://www-cast3m.cea.fr/>.
- `Mardown` (with pandoc <http://pandoc.org/>). 
- `TPlot` <https://github.com/thelfer/tfel-plot>.

The project is still in heavy development. Today (28/02/2018), it is good enough for my daily tasks and can be considered beta quality though no release is planned before months (even in beta). I use it for developping all my `C++` projects, including `TFEL/MFront` and `qemacs` itself, of course.

Following this issue, I started a website: <https://thelfer.github.io/qemacs/>. You will find a few examples of what can be done right now. 

With kind regards,

Thomas Helfer

**Comment by 461353349** [comment]
Fine!Good Idea!
