### ISSUE TITLE
qemacs compiling Mfront file bug in windows

### ISSUE THREAD

**Issue by jamel-tirari** [thelfer/tfel-editor#2]
Hi,

I have an issue when i try to compile an mront file using qemacs on a windows machine : if i select quiet, level3, debug or full in the Verbose Level selection, i get the following error (quiet is selected here) : 

MFront::treatOBuild: unsupported value 'quiet' for the --obuild option

Any help ? thanks in advance and thanks for the great software.

PS : i compiled everything using VS2017 Community, Cmake 3.11.1 and QT 5.11.1

Best Regards,

Jamel.

**Comment by thelfer** [comment]
Hi Jamel,
The issue was not related to `Windows`. There was a bad copy/paste code which led the verbose level to be passed as parameter to the `--obuild` option.
This is now fixed.
Regards,
Thomas

**Comment by jamel-tirari** [comment]
Thanks Thomas, 

indeed, it's fixed now.

Regards,

Jamel.
