### ISSUE TITLE
[Info] there is another qemacs editor

### ISSUE THREAD

**Issue by MarcusE1W** [thelfer/tfel-editor#3]
Hi.

Just to let you know that another editor with the name qemacs exists
https://savannah.nongnu.org/projects/qemacs

**Comment by thelfer** [comment]
Hi Marcus,
You're right. Thank for noticing me. As it mostly started as a project for my own usage, I did not really care about the name.
I guess I shall find a better name as soon as possible.
With kind regards,
Thomas Helfer

**Comment by thelfer** [comment]
Following Marcus fully justified claim, the project is now named `tfel-editor`.
