### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by lewisde** [thelfer/tfel-editor#4]
I cloned the repo to an Arch VM, created a build directory in the project, cd'd to the build directory and ran "cmake ..".

Is there something else I need to do? Does it in fact build and run?

**Comment by thelfer** [comment]
Dear lewisde,

Thank for your interest.

I updated the `INSTALL.md` file at the root of the sources.

I also enclose to this ticket a `ZIP` archive which contains a script (called `install.sh`) that I use under `UniX` to get the latest development versions of `tfel`, `tfel-plot` and `tfel-editor` (`master` branche in each case):

- You must update the installation directory (define at the top of the script)
- this script does nothing if there have been no new commit.
- this script assumes that `Qt` is installed system-wide (could easily be changed)
- the last four builds are kept, to still have a working environment even if a break occured in the latest commit

If the script successfully builds everything, the `tfel-editor` directory will contain an `install` directory (pointing to the latest sucessfull build) containing an `env.sh` file which set up the appropriate environment files to have access to `tfel`, `tfel-plot` and `tfel-editor`.

I hope this helps.

Best,

Thomas
[install.zip](https://github.com/thelfer/tfel-editor/files/2490944/install.zip)

**Comment by thelfer** [comment]
Dear lewisde,

I have updated the build instruction (`INSTALL.md` file) for `Ubuntu 18.1` and `Mageia 6.1`. I will try to give additional information for building `tfel-editor` on `Windows` soon.

If you need some additional information, do not hesitate to reopen this issue.

With kind regards,

Thomas Helfer
