### ISSUE TITLE
Compability

### ISSUE THREAD

**Issue by ShalokShalom** [thelfer/tfel-editor#6]
Hi there :)

Is this a production ready replacement for Emacs - or even meant to be one?

What does "clone" refer to?

Thanks

**Comment by thelfer** [comment]
Hi,

`tfel-editor` is a project meant to create a text editor that leverages the abilities of the `Qt` library which is strongly inspired by `Emacs`. That is how "clone" ought to be interpreted, though this might have been misleading, so I changed the project description. 

Regarding your other questions.

I use it on a daily basis, though far from being production ready.

The main idea was to create a text editor for the various projects that I have created: `mfront` (<https://github.com/thelfer/tfel>), `mtest` (<https://github.com/thelfer/tfel>), `tplot` (<https://github.com/thelfer/tfel-plot>),  `licos` (developed for internal use by the French Atomic and Alternative Energies Commission). 

Aside from those major modes, the `Cast3M`(<http://www-cast3m.cea.fr/>) `C++`, `mardown` and `LaTeX` modes are quite usable. The other modes are "experimental".

You may also find a more complete description of  the project goals here: https://thelfer.github.io/tfel-editor/faq.html

Regards,

**Comment by ShalokShalom** [comment]
oh, I found the former name "qemacs" much more telling ^^

thanks a lot

**Comment by thelfer** [comment]
I also found it much more explicit, but It seeams that it was already used. See <https://github.com/thelfer/tfel-editor/issues/3>.
Best,

**Comment by ShalokShalom** [comment]
I hope you find some middle ground. A Screenshot might help

**Comment by thelfer** [comment]
There are some screenshots available on the website :) See https://thelfer.github.io/tfel-editor/
In particular: https://thelfer.github.io/tfel-editor/mfront-major-mode.html
More seriously, `tfel-editor` works but it lacks proper documentation and without this advertising is pretty much useless.
